/**
 * @agentboster/sdk — public surface for building agentboster extensions,
 * skills, prompts, themes, and programmatic agent sessions.
 *
 * This package is a curated re-export of `@agentboster-cli/core` (the
 * runtime). When an extension is loaded inside the runtime, the host
 * injects the real `@agentboster-cli/core` via a virtual-module alias,
 * so every type and value declared by the runtime flows through
 * automatically. There is no separate SDK implementation to drift out
 * of sync.
 *
 * Exports are listed explicitly (rather than `export *`) so the SDK can
 * type-check standalone against the minimal stub in `vendor/core.d.ts`.
 * To regenerate this file after a runtime change:
 *
 *     python3 subpackage/sdk/scripts/regen-stubs.py
 *     python3 subpackage/sdk/scripts/regen-exports.py
 *
 * @example Minimal extension
 * ```ts
 * import { Type } from 'typebox';
 * import type { ExtensionAPI } from '@agentboster/sdk';
 *
 * export default function (pi: ExtensionAPI): void {
 *   pi.registerTool({
 *     name: 'hello',
 *     label: 'Hello',
 *     description: 'Say hello to someone.',
 *     parameters: Type.Object({ name: Type.Optional(Type.String()) }),
 *     async execute(_id, params) {
 *       return {
 *         content: [{ type: 'text', text: `Hello, ${params.name ?? 'world'}!` }],
 *       };
 *     },
 *   });
 * }
 * ```
 *
 * See `examples/` for complete working extensions.
 *
 * @packageDocumentation
 */

// ── Full runtime re-export (explicit; regen via scripts/regen-exports.py) ──
// We don't use `export *` so the SDK type-checks standalone against
// vendor/core.d.ts. When the runtime adds an export, regenerate this file.

export type {
  AgentEndEvent,
  AgentSessionConfig,
  AgentSessionEvent,
  AgentSessionEventListener,
  AgentSessionRuntimeDiagnostic,
  AgentSessionServices,
  AgentStartEvent,
  AgentToolResult,
  AgentToolUpdateCallback,
  AppKeybinding,
  Args,
  AuthCredential,
  AuthStatus,
  AuthStorageData,
  AutocompleteProviderFactory,
  BashOperations,
  BashSpawnContext,
  BashSpawnHook,
  BashToolCallEvent,
  BashToolDetails,
  BashToolInput,
  BashToolOptions,
  BeforeAgentStartEvent,
  BeforeAgentStartEventResult,
  BeforeProviderRequestEvent,
  BeforeProviderRequestEventResult,
  BranchPreparation,
  BranchSummaryEntry,
  BranchSummaryResult,
  BuildSystemPromptOptions,
  CollectEntriesResult,
  CompactOptions,
  CompactionEntry,
  CompactionResult,
  CompactionSettings,
  ComputerUseToolDetails,
  ContextEvent,
  ContextUsage,
  CreateAgentSessionFromServicesOptions,
  CreateAgentSessionOptions,
  CreateAgentSessionResult,
  CreateAgentSessionRuntimeFactory,
  CreateAgentSessionRuntimeResult,
  CreateAgentSessionServicesOptions,
  CustomEntry,
  CustomMessageEntry,
  CustomToolCallEvent,
  CutPointResult,
  DefaultProjectTrust,
  DiscoveredMcpService,
  EditDiffResult,
  EditOperations,
  EditToolCallEvent,
  EditToolDetails,
  EditToolInput,
  EditToolOptions,
  EventBus,
  EventBusController,
  ExecOptions,
  ExecResult,
  Extension,
  ExtensionAPI,
  ExtensionActions,
  ExtensionCommandContext,
  ExtensionCommandContextActions,
  ExtensionContext,
  ExtensionContextActions,
  ExtensionError,
  ExtensionEvent,
  ExtensionFactory,
  ExtensionFlag,
  ExtensionHandler,
  ExtensionRuntime,
  ExtensionShortcut,
  ExtensionUIContext,
  ExtensionUIDialogOptions,
  ExtensionWidgetOptions,
  FileEntry,
  FileOperations,
  FindOperations,
  FindToolCallEvent,
  FindToolDetails,
  FindToolInput,
  FindToolOptions,
  GenerateBranchSummaryOptions,
  GetApiKeyOptions,
  GetAxAtPointToolInput,
  GetFocusedAxToolInput,
  GrepOperations,
  GrepToolCallEvent,
  GrepToolDetails,
  GrepToolInput,
  GrepToolOptions,
  ImageSettings,
  InputEvent,
  InputEventResult,
  InputSource,
  InteractiveModeOptions,
  KeyEventToolInput,
  KeybindingsManager,
  LoadExtensionsResult,
  LoadSkillsFromDirOptions,
  LoadSkillsResult,
  LsOperations,
  LsToolCallEvent,
  LsToolDetails,
  LsToolInput,
  LsToolOptions,
  MainOptions,
  McpServiceProtocol,
  McpServiceSource,
  MessageRenderOptions,
  MessageRenderer,
  ModelChangeEntry,
  ModelCycleResult,
  ModelInfo,
  MouseClickToolInput,
  MouseDragToolInput,
  MouseMoveToolInput,
  NewSessionOptions,
  PackageManager,
  PackageSource,
  ParsedSkillBlock,
  PathMetadata,
  PrintModeOptions,
  ProgressCallback,
  ProgressEvent,
  ProjectTrustContext,
  ProjectTrustDecision,
  ProjectTrustEvent,
  ProjectTrustEventDecision,
  ProjectTrustEventResult,
  ProjectTrustHandler,
  ProjectTrustStoreEntry,
  ProjectTrustUpdate,
  PromptOptions,
  PromptTemplate,
  ProviderConfig,
  ProviderModelConfig,
  ReadOperations,
  ReadToolCallEvent,
  ReadToolDetails,
  ReadToolInput,
  ReadToolOptions,
  ReadonlyFooterDataProvider,
  RegisteredCommand,
  RegisteredTool,
  RenderDiffOptions,
  ResizedImage,
  ResolvedCommand,
  ResolvedPaths,
  ResolvedResource,
  ResourceCollision,
  ResourceDiagnostic,
  ResourceLoader,
  RetrySettings,
  RpcClientOptions,
  RpcCommand,
  RpcEventListener,
  RpcExtensionUIRequest,
  RpcExtensionUIResponse,
  RpcResponse,
  RpcSessionState,
  RunningMcpService,
  ScreenshotToolInput,
  SessionBeforeCompactEvent,
  SessionBeforeForkEvent,
  SessionBeforeSwitchEvent,
  SessionBeforeTreeEvent,
  SessionCompactEvent,
  SessionContext,
  SessionEntry,
  SessionEntryBase,
  SessionHeader,
  SessionInfo,
  SessionInfoEntry,
  SessionMessageEntry,
  SessionShutdownEvent,
  SessionStartEvent,
  SessionStats,
  SessionTreeEvent,
  SettingsCallbacks,
  SettingsConfig,
  SettingsManagerCreateOptions,
  Skill,
  SkillFrontmatter,
  SlashCommandInfo,
  SlashCommandSource,
  SourceInfo,
  TerminalInputHandler,
  ThemeColor,
  ThinkingLevelChangeEntry,
  ToolCallEvent,
  ToolCallEventResult,
  ToolDefinition,
  ToolExecutionMode,
  ToolExecutionOptions,
  ToolInfo,
  ToolRenderResultOptions,
  ToolResultEvent,
  ToolsOptions,
  TruncationOptions,
  TruncationResult,
  TurnEndEvent,
  TurnStartEvent,
  TypeTextToolInput,
  UserBashEvent,
  UserBashEventResult,
  VisualTruncateResult,
  WidgetPlacement,
  WorkingIndicatorOptions,
  WriteOperations,
  WriteToolCallEvent,
  WriteToolInput,
  WriteToolOptions,
} from '@agentboster-cli/core';

export {
  AgentSession,
  AgentSessionRuntime,
  ArminComponent,
  AssistantMessageComponent,
  AuthStorage,
  BashExecutionComponent,
  BorderedLoader,
  BranchSummaryMessageComponent,
  CONFIG_DIR_NAME,
  CURRENT_SESSION_VERSION,
  CompactionSummaryMessageComponent,
  CustomEditor,
  CustomMessageComponent,
  DEFAULT_COMPACTION_SETTINGS,
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  DefaultPackageManager,
  DefaultResourceLoader,
  DynamicBorder,
  ExtensionEditorComponent,
  ExtensionInputComponent,
  ExtensionRunner,
  ExtensionSelectorComponent,
  FooterComponent,
  InteractiveMode,
  McpServiceManager,
  ModelRegistry,
  ModelSelectorComponent,
  ProjectTrustStore,
  RpcClient,
  SessionManager,
  SessionSelectorComponent,
  SettingsManager,
  SettingsSelectorComponent,
  ShowImagesSelectorComponent,
  SkillInvocationMessageComponent,
  Theme,
  ThemeSelectorComponent,
  ToolExecutionComponent,
  TreeSelectorComponent,
  UserMessageComponent,
  UserMessageSelectorComponent,
  VERSION,
  buildSessionContext,
  calculateContextTokens,
  collectEntriesForBranchSummary,
  compact,
  convertToLlm,
  convertToPng,
  copyToClipboard,
  createAgentSessionFromServices,
  createAgentSessionRuntime,
  createAgentSessionServices,
  createBashTool,
  createBashToolDefinition,
  createComputerUseToolDefinitions,
  createEditTool,
  createEditToolDefinition,
  createEventBus,
  createExtensionRuntime,
  createFindTool,
  createFindToolDefinition,
  createGrepTool,
  createGrepToolDefinition,
  createLocalBashOperations,
  createLsTool,
  createLsToolDefinition,
  createReadOnlyTools,
  createReadTool,
  createReadToolDefinition,
  createSyntheticSourceInfo,
  createWriteTool,
  createWriteToolDefinition,
  defineTool,
  discoverAndLoadExtensions,
  discoverMcpServices,
  estimateTokens,
  findCutPoint,
  findTurnStartIndex,
  formatDimensionNote,
  formatSize,
  formatSkillsForPrompt,
  generateBranchSummary,
  generateDiffString,
  generateSummary,
  generateUnifiedPatch,
  getAgentDir,
  getDocsPath,
  getExamplesPath,
  getLanguageFromPath,
  getLastAssistantUsage,
  getLatestCompactionEntry,
  getMarkdownTheme,
  getPackageDir,
  getReadmePath,
  getSelectListTheme,
  getSettingsListTheme,
  getShellConfig,
  hasTrustRequiringProjectResources,
  highlightCode,
  initTheme,
  isBashToolResult,
  isEditToolResult,
  isFindToolResult,
  isGrepToolResult,
  isLsToolResult,
  isReadToolResult,
  isToolCallEventType,
  isWriteToolResult,
  keyHint,
  keyText,
  loadProjectContextFiles,
  loadSkills,
  loadSkillsFromDir,
  main,
  migrateSessionEntries,
  parseArgs,
  parseFrontmatter,
  parseSessionEntries,
  parseSkillBlock,
  prepareBranchEntries,
  rawKeyHint,
  renderDiff,
  resizeImage,
  runPrintMode,
  runRpcMode,
  serializeConversation,
  shouldCompact,
  stripFrontmatter,
  truncateHead,
  truncateLine,
  truncateTail,
  truncateToVisualLines,
  withFileMutationQueue,
  wrapRegisteredTool,
  wrapRegisteredTools,
} from '@agentboster-cli/core';

// ── SDK-only compatibility helpers ──────────────────────────────
export { resolveModelApiKey } from './compat.js';
