import type { L0Rule } from './types';

export const DEFAULT_L0_RULES: L0Rule[] = [
  {
    id: 'l0-001',
    name: 'Block rm -rf /',
    description: 'Prevents catastrophic deletion of root filesystem',
    pattern: 'rm\\s+(-[rfRF]+\\s+)+/',
    patternType: 'regex',
    action: 'block',
    notifyOnBlock: true,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 1000,
    enabled: true,
  },
  {
    id: 'l0-002',
    name: 'Block mkfs',
    description: 'Prevents filesystem formatting commands',
    pattern: 'mkfs\\..*',
    patternType: 'regex',
    action: 'block',
    notifyOnBlock: true,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 990,
    enabled: true,
  },
  {
    id: 'l0-003',
    name: 'Block dd',
    description: 'Prevents direct disk write commands',
    pattern: 'dd\\s+.*',
    patternType: 'regex',
    action: 'block',
    notifyOnBlock: true,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 980,
    enabled: true,
  },
  {
    id: 'l0-004',
    name: 'Block /etc/shadow access',
    description: 'Prevents access to password hash file',
    pattern: '.*(/etc/shadow).*',
    patternType: 'regex',
    action: 'block',
    notifyOnBlock: true,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 970,
    enabled: true,
  },
  {
    id: 'l0-005',
    name: 'Block chmod 777',
    description: 'Prevents setting world-writable permissions',
    pattern: 'chmod\\s+(777|666|a+rwx).*',
    patternType: 'regex',
    action: 'escalate',
    notifyOnBlock: true,
    allowTemporaryOverride: true,
    overrideWindowSeconds: 600,
    priority: 960,
    enabled: true,
  },
  {
    id: 'l0-006',
    name: 'Block dangerous git operations',
    description: 'Prevents destructive git operations',
    pattern: 'git\\s+(reset\\s+--hard|checkout\\s+--|clean\\s+-[fd]+).*',
    patternType: 'regex',
    action: 'escalate',
    notifyOnBlock: true,
    allowTemporaryOverride: true,
    overrideWindowSeconds: 300,
    priority: 950,
    enabled: true,
  },
  {
    id: 'l0-007',
    name: 'Allow read-only git commands',
    description: 'Allows safe git read operations',
    pattern: 'git\\s+(status|log|diff|show|branch|remote|stash\\s+list).*',
    patternType: 'regex',
    action: 'allow',
    notifyOnBlock: false,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 500,
    enabled: true,
  },
  {
    id: 'l0-008',
    name: 'Allow safe file operations',
    description: 'Allows common read operations',
    pattern: '(ls|cat|head|tail|less|more|find|grep|wc|du|df)\\s+.*',
    patternType: 'regex',
    action: 'allow',
    notifyOnBlock: false,
    allowTemporaryOverride: false,
    overrideWindowSeconds: 0,
    priority: 400,
    enabled: true,
  },
  {
    id: 'l0-009',
    name: 'Escalate network operations',
    description: 'Escalates potentially risky network operations',
    pattern: '(curl|wget|nc|nmap|telnet)\\s+.*',
    patternType: 'regex',
    action: 'escalate',
    notifyOnBlock: false,
    allowTemporaryOverride: true,
    overrideWindowSeconds: 300,
    priority: 800,
    enabled: true,
  },
  {
    id: 'l0-010',
    name: 'Escalate package installations',
    description: 'Escalates package manager operations',
    pattern:
      '(npm\\s+install|pip\\s+install|apt\\s+install|yum\\s+install|brew\\s+install).*',
    patternType: 'regex',
    action: 'escalate',
    notifyOnBlock: false,
    allowTemporaryOverride: true,
    overrideWindowSeconds: 600,
    priority: 750,
    enabled: true,
  },
];
