import {
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { agentBarriers } from './agent-barriers';

/**
 * agentSubagentBatches + agentSubagentJobs: durable storage for the
 * subAgent tool's spawn/spawn_async batches.
 *
 * Phase C-full of the multi-agent collaboration design. Previously
 * (phases A/C-mini) subAgent persisted its state as a jsonb blob in
 * sessions.metadata.workflowSubagents. That worked but:
 *   - the read-merge-write pattern couldn't be safely concurrent
 *   - queries by batchId or status required scanning the whole blob
 *   - the schema was implicit (Record<string, any>), not enforceable
 *
 * These tables give the subAgent tool a real persistence layer. The
 * in-process `activeSubagentBatches` Map (in sub-agent.ts) stays as a
 * hot cache for AbortControllers + Promise tracking; everything
 * observable (state, summary, status) flows here.
 *
 * Read-time lazy migration: if a batch is missing from these tables
 * but exists in sessions.metadata.workflowSubagents (the legacy path),
 * the DB layer transparently backfills it. This avoids a separate
 * migration script — the first read after deploy self-heals.
 */

export const agentSubagentBatches = pgTable(
  'agent_subagent_batches',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    /** Stable id generated by the subAgent tool (wf-subagent-batch-XXX). */
    batchId: text('batch_id').notNull().unique(),
    sessionId: uuid('session_id'),
    runId: text('run_id'),
    /** Optional phase-A barrier this batch is linked to (spawn_async). */
    barrierId: text('barrier_id').references(() => agentBarriers.barrierId, {
      onDelete: 'set null',
    }),
    status: text('status', {
      enum: ['running', 'completed', 'failed', 'cancelled'],
    })
      .default('running')
      .notNull(),
    concurrencyLimit: integer('concurrency_limit').notNull().default(1),
    /** Counter cache for fast query/UI reads. equals COUNT(jobs WHERE
     *  status='completed'/'failed'/'cancelled'). Maintained by the
     *  DB layer's updateJob function in the same transaction. */
    succeeded: integer('succeeded').default(0).notNull(),
    failed: integer('failed').default(0).notNull(),
    cancelled: integer('cancelled').default(0).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('agent_subagent_batches_session_idx').on(table.sessionId),
    index('agent_subagent_batches_status_idx').on(table.status),
    index('agent_subagent_batches_barrier_idx').on(table.barrierId),
  ],
);

export const agentSubagentJobs = pgTable(
  'agent_subagent_jobs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    /** Stable id generated by the subAgent tool (wf-subagent-XXX). */
    subagentId: text('subagent_id').notNull().unique(),
    /** FK target is the uuid PK on agentSubagentBatches; this is the
     *  human-readable stable id used for fast lookups. */
    batchStableId: text('batch_stable_id').notNull(),
    sessionId: uuid('session_id'),
    agentName: text('agent_name').notNull(),
    task: text('task').notNull(),
    status: text('status', {
      enum: ['queued', 'running', 'completed', 'failed', 'cancelled'],
    })
      .default('queued')
      .notNull(),
    modelId: text('model_id'),
    steps: integer('steps'),
    summary: text('summary'),
    error: text('error'),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('agent_subagent_jobs_batch_idx').on(table.batchStableId),
    index('agent_subagent_jobs_session_idx').on(table.sessionId),
    index('agent_subagent_jobs_status_idx').on(table.status),
    uniqueIndex('agent_subagent_jobs_subagent_id_idx').on(table.subagentId),
  ],
);

export type AgentSubagentBatch = typeof agentSubagentBatches.$inferSelect;
export type NewAgentSubagentBatch = typeof agentSubagentBatches.$inferInsert;
export type AgentSubagentJob = typeof agentSubagentJobs.$inferSelect;
export type NewAgentSubagentJob = typeof agentSubagentJobs.$inferInsert;
