import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * agentBarriers persists cross-agent synchronization points.
 *
 * Stage A of the multi-agent collaboration design: a durable, DB-backed
 * barrier primitive that lets a workflow fan out N participants and block
 * until a release condition is met (all / quorum / first_ok / first_fail).
 *
 * The in-process BarrierRegistry (lib/workflow/agent/barrier.ts) is a hot
 * cache in front of this layer; every create/release/cancel touches both.
 * On startup the registry rehydrates from this table so an in-memory
 * Vercel instance picks up barriers that survived from a previous deploy.
 *
 * Status lifecycle:
 *   open → released | cancelled | expired
 * A row in `open` is considered active (waiters may still be waiting).
 *
 * sessionId is nullable so a barrier can coordinate work that crosses
 * session boundaries (Stage B of the design); when set it scopes queries
 * for UI/admin surfaces.
 */
export const agentBarriers = pgTable(
  'agent_barriers',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    /** Stable identifier generated by the barrier creator. */
    barrierId: text('barrier_id').notNull().unique(),
    sessionId: uuid('session_id'),
    /** Workflow run that owns this barrier (may differ from sessionId
     *  when the barrier is created by a nested step or a different run). */
    runId: text('run_id'),
    /** Expected number of release() calls before the barrier releases. */
    expected: integer('expected').notNull(),
    /** Number of release() calls observed so far (atomic increment on
     *  each release; see agentBarrierReleases for the append-only audit
     *  trail that backs this counter). */
    released: integer('released').default(0).notNull(),
    mode: text('mode', {
      enum: ['all', 'quorum', 'first_ok', 'first_fail'],
    })
      .default('all')
      .notNull(),
    /** When mode='quorum', the minimum number of ok releases required. */
    quorum: integer('quorum'),
    status: text('status', {
      enum: ['open', 'released', 'cancelled', 'expired'],
    })
      .default('open')
      .notNull(),
    /** Aggregated view of all participant payloads at release time.
     *  Mirrors agentBarrierReleases for cheap reads by waiters/UI. */
    result: jsonb('result').$type<{
      ok: boolean;
      releases: Array<{
        participantId: string;
        ok: boolean;
        payload?: unknown;
        releasedAt: string;
      }>;
      releasedAt?: string;
      reason?: string;
    }>(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    /** When the barrier actually released (terminal transition time). */
    releasedAt: timestamp('released_at', { withTimezone: true }),
    /** Optional absolute deadline; the watchdog marks the barrier
     *  expired after this point even if not fully released. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
  },
  (table) => [
    index('agent_barriers_status_idx').on(table.status),
    index('agent_barriers_session_idx').on(table.sessionId),
    index('agent_barriers_run_idx').on(table.runId),
  ],
);

/**
 * Append-only audit trail of who released a barrier and what they
 * contributed. One row per (barrier, participant) pair; the
 * (barrier_id, participant_id) unique index makes release() idempotent
 * — a participant that calls release twice only counts once.
 */
export const agentBarrierReleases = pgTable(
  'agent_barrier_releases',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    barrierId: text('barrier_id')
      .notNull()
      .references(() => agentBarriers.id, { onDelete: 'cascade' }),
    /** Stable barrier_id (FK target is the uuid PK; this is the
     *  human-readable id used in the registry for fast lookups). */
    barrierStableId: text('barrier_stable_id').notNull(),
    /** Logical name of the participant (sub-agent id, task id, etc). */
    participantId: text('participant_id').notNull(),
    ok: boolean('ok').notNull(),
    payload: jsonb('payload'),
    releasedAt: timestamp('released_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('agent_barrier_releases_barrier_idx').on(table.barrierStableId),
    uniqueIndex('agent_barrier_releases_barrier_participant_idx').on(
      table.barrierStableId,
      table.participantId,
    ),
  ],
);

export type AgentBarrier = typeof agentBarriers.$inferSelect;
export type NewAgentBarrier = typeof agentBarriers.$inferInsert;
export type AgentBarrierRelease = typeof agentBarrierReleases.$inferSelect;
export type NewAgentBarrierRelease = typeof agentBarrierReleases.$inferInsert;
