import {
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * l2Decisions persists pending/sent/resolved/expired decisions.
 *
 * P0.2: Previously the DecisionQueue lived only in process memory, so
 * every Vercel redeploy or serverless cold start wiped all pending L2
 * authorizations and questions. This table is the durable backing store;
 * the in-memory queue is now a hot cache in front of it.
 *
 * Status lifecycle:
 *   pending → sent → resolved | denied | expired | timeout
 * A row in `pending` or `sent` is considered "active" (visible to UI).
 */
export const l2Decisions = pgTable(
  'l2_decisions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    /** Stable identifier generated by the daemon or web UI; unique. */
    decisionId: text('decision_id').notNull().unique(),
    taskId: text('task_id').notNull(),
    sessionId: text('session_id').notNull(),
    agentId: text('agent_id').notNull(),
    /** 'l2_auth' | 'question' | 'conflict' | 'branch' */
    type: text('type').notNull(),
    /**
     * 'pending' | 'sent' | 'resolved' | 'denied' | 'expired' | 'timeout'
     * `denied` is a terminal resolution (= user clicked reject).
     * `resolved` is a terminal resolution (= user clicked pass/answer).
     * `expired`/`timeout` are terminal states from the watchdog.
     */
    status: text('status').default('pending').notNull(),
    /** Full decision payload (command/score/reason/question/options/...). */
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
    /** User reply once resolved (action + optional answers/time input). */
    resolution: jsonb('resolution').$type<Record<string, unknown> | null>(),
    /** Who resolved it (user id, or 'system' for timeouts). */
    resolvedBy: text('resolved_by'),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    /** Daemon node that originated the request (for forwarding replies). */
    nodeId: text('node_id'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    index('l2_decisions_status_created_idx').on(table.status, table.createdAt),
    index('l2_decisions_session_idx').on(table.sessionId),
    index('l2_decisions_task_idx').on(table.taskId),
  ],
);

export type L2Decision = typeof l2Decisions.$inferSelect;
export type NewL2Decision = typeof l2Decisions.$inferInsert;
