// Source: subpackage/cli/packages/desktop/src/rpc/bridge.ts (lines 8-130)
//
// Type contracts for the RPC bridge. The Desktop renderer's `RpcBridge`
// class is the runtime that owns these types; this file mirrors the
// type-only surface 1:1 so SDK consumers can call `rpc_start`,
// interpret `RpcSessionState`, etc., without taking a runtime
// dependency on `@tauri-apps/api`.
//
// DO NOT add types here that are not already exported from bridge.ts.
// When a type changes there, run `scripts/regen-desktop.py` to detect
// drift (it diffs this file against bridge.ts's export list).

/** Source: bridge.ts:8 */
export type QueueMode = 'all' | 'one-at-a-time';

/** Source: bridge.ts:9 */
export type StreamingBehavior = 'steer' | 'followUp';

/** Source: bridge.ts:10 */
export type ClientSpoof = 'off' | 'on';

/** Source: bridge.ts:11-17 */
export type ThinkingLevel =
  | 'off'
  | 'minimal'
  | 'low'
  | 'medium'
  | 'high'
  | 'xhigh';

/**
 * Options passed to the `rpc_start` Tauri command.
 *
 * Source: bridge.ts:19-38
 *
 * NOTE: bridge.ts uses camelCase field names here (not snake_case),
 * because the renderer constructs this object directly. The bridge
 * translates to snake_case on the way to Rust (see bridge.ts:328-340).
 * SDK consumers that invoke `rpc_start` directly via `invokeTyped`
 * should use the snake_case `RpcStartWireOptions` shape exposed in
 * `invoke.ts`.
 */
export interface RpcStartOptions {
  cliPath: string | null;
  piPath?: string | null;
  cwd: string;
  provider?: string;
  model?: string;
  env?: Record<string, string>;
  /**
   * Web backend base URL. When set together with `sessionId`, the CLI
   * registers itself online for this session so Web-side tool providers
   * (computer-use-remote) can dispatch to it. Optional — if absent, the
   * CLI stays in pure local RPC mode (Desktop-only, no remote LLM path).
   */
  backendUrl?: string | null;
  /**
   * Web-side CLI session id. Generated by the Desktop renderer (UUID)
   * and reused across reconnects within the same chat session.
   */
  sessionId?: string | null;
}

/** Source: bridge.ts:40-44 */
export interface RpcImageInput {
  type: 'image';
  data: string;
  mimeType: string;
}

/** Source: bridge.ts:46-49 */
export interface RpcPromptOptions {
  images?: RpcImageInput[];
  streamingBehavior?: StreamingBehavior;
}

/** Source: bridge.ts:51-70 */
export interface RpcSessionState {
  model?: {
    provider: string;
    id: string;
    contextWindow?: number;
    reasoning?: boolean;
  };
  thinkingLevel: ThinkingLevel;
  isStreaming: boolean;
  isCompacting: boolean;
  steeringMode: QueueMode;
  followUpMode: QueueMode;
  sessionFile?: string;
  sessionId: string;
  sessionName?: string;
  autoCompactionEnabled: boolean;
  clientSpoof: ClientSpoof;
  messageCount: number;
  pendingMessageCount: number;
}

/** Source: bridge.ts:72-77 (also emitted by Rust `run_pi_cli_command`) */
export interface PiCliCommandResult {
  stdout: string;
  stderr: string;
  exit_code: number;
  discovery: string;
}

/**
 * Provider auth status — referenced by `auth/provider-auth.ts`,
 * `chat-view.ts`, and `model-picker-provider-groups.ts`.
 *
 * Source: bridge.ts:84-88
 */
export interface PiAuthProviderStatus {
  provider: string;
  source: 'auth_file_api_key' | 'auth_file_oauth' | 'environment';
  kind: 'api_key' | 'oauth' | 'unknown';
}

/** Source: bridge.ts:90 */
export type McpServiceProtocol = 'mcp' | 'lsp';

/** Source: bridge.ts:91 */
export type McpServiceSource = 'builtin' | 'project-config';

/** Source: bridge.ts:93-108 */
export interface DiscoveredMcpService {
  id: string;
  name: string;
  protocol: McpServiceProtocol;
  description: string;
  command: string;
  args: string[];
  cwd: string;
  envKeys: string[];
  source: McpServiceSource;
  sourcePath?: string;
  installed: boolean;
  executablePath: string | null;
  projectDetected: boolean;
  reason: string;
}

/** Source: bridge.ts:110-123 */
export interface RunningMcpService {
  id: string;
  name: string;
  protocol: McpServiceProtocol;
  command: string;
  args: string[];
  cwd: string;
  pid: number | null;
  startedAt: number;
  running: boolean;
  exitCode: number | null;
  signal: string | null;
  stderrTail: string;
}

/** Source: bridge.ts:125-130 */
export interface RpcCompatibilityReport {
  ok: boolean;
  checks: string[];
  error?: string;
  checkedAt: number;
}
